# Generated by Django 5.2.3 on 2025-11-12 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_date', models.DateTimeField(auto_now_add=True)),
                ('model_type', models.CharField(help_text="e.g., 'Temperature', 'Humidity', 'Rain'", max_length=50)),
                ('model_a_name', models.CharField(max_length=100)),
                ('model_a_version', models.CharField(max_length=20)),
                ('model_a_mae', models.FloatField(blank=True, null=True)),
                ('model_a_rmse', models.FloatField(blank=True, null=True)),
                ('model_a_r2', models.FloatField(blank=True, null=True)),
                ('model_a_accuracy', models.FloatField(blank=True, null=True)),
                ('model_b_name', models.CharField(max_length=100)),
                ('model_b_version', models.CharField(max_length=20)),
                ('model_b_mae', models.FloatField(blank=True, null=True)),
                ('model_b_rmse', models.FloatField(blank=True, null=True)),
                ('model_b_r2', models.FloatField(blank=True, null=True)),
                ('model_b_accuracy', models.FloatField(blank=True, null=True)),
                ('winner', models.CharField(choices=[('A', 'Model A'), ('B', 'Model B'), ('TIE', 'Tie')], max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Model Comparison Result',
                'verbose_name_plural': 'Model Comparison Results',
                'ordering': ['-comparison_date'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('rain_model_version', models.CharField(max_length=20)),
                ('temp_model_version', models.CharField(max_length=20)),
                ('humidity_model_version', models.CharField(max_length=20)),
                ('input_features', models.TextField(help_text='JSON string of input features')),
                ('rain_prediction', models.IntegerField(help_text='0 or 1')),
                ('rain_probability', models.FloatField(blank=True, null=True)),
                ('temp_predictions', models.TextField(help_text='JSON array of 5 temperature predictions')),
                ('humidity_predictions', models.TextField(help_text='JSON array of 5 humidity predictions')),
                ('temp_lower_bounds', models.TextField(blank=True, null=True)),
                ('temp_upper_bounds', models.TextField(blank=True, null=True)),
                ('humidity_lower_bounds', models.TextField(blank=True, null=True)),
                ('humidity_upper_bounds', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_unit', models.CharField(choices=[('celsius', 'Celsius'), ('fahrenheit', 'Fahrenheit')], default='celsius', max_length=10)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=10)),
                ('email_alerts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('high_temp', 'High Temperature'), ('low_temp', 'Low Temperature'), ('rain', 'Rain Expected'), ('high_humidity', 'High Humidity'), ('storm', 'Storm Warning')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('threshold_value', models.FloatField(help_text='The threshold that triggered the alert')),
                ('actual_value', models.FloatField(help_text='The actual value that exceeded threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weather Alert',
                'verbose_name_plural': 'Weather Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite City',
                'verbose_name_plural': 'Favorite Cities',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'city_name')},
            },
        ),
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('rain_rf', 'Rain Random Forest'), ('rain_xgb', 'Rain XGBoost'), ('temp_rf', 'Temperature Random Forest'), ('temp_lstm', 'Temperature LSTM'), ('humidity_rf', 'Humidity Random Forest'), ('humidity_lstm', 'Humidity LSTM')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Squared Error', null=True)),
                ('r2_score', models.FloatField(blank=True, help_text='R² Score', null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(blank=True, null=True)),
                ('test_samples', models.IntegerField(blank=True, null=True)),
                ('hyperparameters', models.TextField(help_text='JSON string of hyperparameters')),
                ('features_used', models.TextField(help_text='JSON string of feature names')),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Metadata',
                'verbose_name_plural': 'Model Metadata',
                'ordering': ['-trained_at'],
                'unique_together': {('model_type', 'version')},
            },
        ),
    ]
